### ISSUE TITLE
Fill in list of GitHub/BitBucket organizations controlled by Government of Canada

### ISSUE THREAD

**Issue by jpmckinney** [canada-ca/welcome#12]
@nschonni wrote in #10:

> https://github.com/github/government.github.com/blob/9252298d8fe4bf8645681e09fcb10d041958a75f/_data/governments.yml#L89 has a more complete list

**Comment by jpmckinney** [comment]
GitHub orgs to add:

* AAFC-MBB
* CIHR
* ECCC-MSC
* GeoCanViz
* goc
* HIFIS
* MC-MBO-WebPublishingTeam
* RAMP-PCAR
* ServiceCanada
* TBS-EACPD

**Comment by MaryBethBaker** [comment]
@smellems  Did you see this list?

**Comment by nschonni** [comment]
The github site has this helper script it uses to pull in changed orgs https://github.com/github/government.github.com/blob/gh-pages/script/fetch-us
It is currently broken though :frowning_face:, looking to see if I can find the new API end point for them. Not sure if we have a Canadian equivalent

**Comment by smellems** [comment]
Yes, I had seen it before, but did not find it this morning.  Also I was thinking a list of GC orgs.  Not including provincial and municipal.

**Comment by patcon** [comment]
@nschonni that script uses the US Digital Registry, which is actually open source:
https://github.com/GSA/us-digital-registry

It could actually be community-hosted, and limit specific email domains to edit/claim accounts: canada.ca or toronto.ca or through some whitelist.

Seems like this could be a fun community project, if someone at CTTO or YOW CivicTech wants to run with it :)

**Comment by smellems** [comment]
I added most of the orgs listed above.  These two have no public repos:

* CIHR
* HIFIS

Also, now we have two "Government of Canada" orgs

**Comment by jpmckinney** [comment]
Thanks @smellems - closing the issue as you've resolved it. Others can open new issues about the scripting options discussed.
