### ISSUE TITLE
Add another organization to list

### ISSUE THREAD

**Issue by jpmckinney** [canada-ca/welcome#14]
* https://github.com/fgpv-vpgf

**Comment by nschonni** [comment]
Do you want to create a PR over at https://github.com/github/government.github.com?

**Comment by jpmckinney** [comment]
This issue is to add it to https://github.com/canada-ca/welcome/blob/master/Organizations-Organisations.md

I don't know what English and French name to use, so can't prepare the PR for this repo.

**Comment by nschonni** [comment]
Created https://github.com/github/government.github.com/pull/535

**Comment by jpmckinney** [comment]
Closing in favor of #15
