### ISSUE TITLE
Watson Tone Analyzer

### ISSUE THREAD

**Issue by robotbotman** [canada-ca/welcome#18]
I was exploring the emotional intelligence category of solutions/tools and came across this: 

https://github.com/watson-developer-cloud/tone-analyzer-nodejs

It seems to be multi-lingual. Has anyone tested this within GC to analyze contextual language/tone/text?

**Comment by robobotman** [comment]
Je faisais des recherches dans la catégorie d’outils permettant de « détecter les émotions » afin d’analyser les expressions faciales et les commentaires écrits ou prononcés, et je suis tombé sur ceci :

https://github.com/watson-developer-cloud/tone-analyzer-nodejs

Ce logiciel semble être multilingue. Quelqu’un au gouvernement fédéral l’a-t-il mis à l’essai pour analyser la rétroaction visuelle et textuelle?

**Comment by MaryBethBaker** [comment]
Archiving this issue.
