### ISSUE TITLE
Can you help us make a list of open source engagement tools? / Pouvez-vous nous aider à dresser une liste des outils de mobilisation provenant de sources ouvertes?

### ISSUE THREAD

**Issue by laurawesley** [canada-ca/welcome#20]
(le français suit...)

The public engagement team at Privy Council Office, along with our friends and colleagues in the Consultations Community of Practice, need your help!

We want to make a list of existing open source engagement tools that governments can use to meaningfully engage large numbers of their citizens. By large numbers, I mean hundreds of thousands up to millions.

For example, [some of you told us](https://github.com/canada-ca/welcome/issues/4#issuecomment-263077398) about pol.is which originated from Seattle and is [being used successfully in Taiwan](https://blog.pol.is/pol-is-in-taiwan-da7570d372b5) within the context of a [radically transparent approach to public engagement](https://blog.pol.is/uber-responds-to-vtaiwans-coherent-blended-volition-3e9b75102b9b).

For each suggestion, please provide a link to the GitHub repository and a case study where government or non-profit organizations have used the tool. It would also be great if you could say the extent to which they are internationalized (in short: can have interfaces in multiple languages so users can toggle between them) and/or compliant to [Web Content Accessibility Guidelines](https://www.w3.org/TR/WCAG/).

Our next step will be to evaluate or group them so we can match each tool with various goals of engagement. We may also try to pilot some of them if we can make them bilingual and accessible, to comply with the [Government of Canada Web Standards](https://www.canada.ca/en/treasury-board-secretariat/topics/government-communications.html).

----
Pouvez-vous nous aider à dresser une liste des outils de mobilisation provenant de sources ouvertes?
L’Équipe de mobilisation du public du Bureau du Conseil privé et ses amis et collègues de la Communauté de pratique des consultations ont besoin de vous!

Nous voulons dresser une liste actuelle des outils de mobilisation provenant de sources ouvertes que les gouvernements peuvent consulter pour prendre contact de façon significative avec un grand nombre de citoyens. J’entends par « grand nombre » des centaines de milliers, voire des millions.

Par exemple, [certains d’entre vous nous ont parlé](https://github.com/canada-ca/welcome/issues/4#issuecomment-263077398) de pol.is qui provient de Seattle et qui [connaît beaucoup de succès à Taiwan](https://blog.pol.is/pol-is-in-taiwan-da7570d372b5) (en anglais seulement) dans le contexte d’une [approche radicalement transparente à l’égard de la mobilisation du public](https://blog.pol.is/uber-responds-to-vtaiwans-coherent-blended-volition-3e9b75102b9b) (en anglais seulement).

Pour chaque suggestion, veuillez nous fournir le lien au répertoire GitHub ainsi qu’une étude de cas décrivant son utilisation par un gouvernement ou une organisation sans but lucratif. Ce serait également fort apprécié si vous pouviez indiquer dans quelle mesure l’outil est international (bref, l’interface est multilingue permettant aux utilisateurs de basculer entre les choix de langues) ou conforme aux [Règles pour l’accessibilité des contenus Web](http://www.w3.org/TR/WCAG/) (en anglais seulement).

La prochaine étape sera d’évaluer ou de regrouper les outils afin de pouvoir jumeler chacun et les divers objectifs de mobilisation. Nous pourrions également en mettre quelques-uns à l’essai si on peut les rendre bilingues et accessibles afin de respecter la [Norme sur l’accessibilité des sites Web](https://www.canada.ca/fr/secretariat-conseil-tresor/sujets/communications-gouvernementales.html).

**Comment by patcon** [comment]
Great idea! If you'd like, it might be worth stealing a trope from the open source community, called "awesome lists". Basically, communities were feeling ill-equipped to understand the landscape of tools, and so informal protocols for aggregating content is github repos was created:

https://github.com/sindresorhus/awesome#contents
https://github.com/sindresorhus/awesome/blob/master/create-list.md

This is great because it's very findable for the community by knowing the trope and googling "awesome list <topic>". It's mostly just a linguistic focus point, which might be cool to play along with :)

A CivicTechTO affiliate group I'm working with, [EDGI](http://envirodatagov.org/), has also started using this sort of tactic. We also link spreadsheets for the more in-depth comparison, which might be useful here as well:

- [`awesome-website-change-monitoring`](https://github.com/patcon/awesome-website-change-monitoring)
- [Comparison of web archiving software](https://github.com/archivers-space/research/tree/master/web_archiving)

The hope is that we can invite the developer community to participate in maintaining the resource, perhaps linking a "Related Projects" section of their readmes to the shared resource. This will prevent document rot, and ensure the disparate projects are have a small shared space in which intersections might be found :)

It would be very interesting to have a prominent steward of this resource, if that steward has enough flexibility to allow the resource to become what the community wishes it to be. It would be really rad if that steward could be government of canada! :)

**Comment by laurawesley** [comment]
Ok let's do it!

**Comment by patcon** [comment]
Rockin! I'll try to stub one out in the next days or so, and I'll give collab access to anyone who wants access here -- happy to transfer repo to this org (or any other), if it's willing to accept it.

**Comment by MaryBethBaker** [comment]
I've also been told by my colleague @gabrielcossette the following location would be good to check too!

> The platform code is here: https://framagit.org/etalab
BTW, Framagit is a GitHub alternative hosted by the French Framasoft not-for-profit association. Great 100% OSS alternative to GitHub with better privacy terms.

**Comment by boydjaimie** [comment]
Some of these options might be good: https://ogptoolbox.org/fr/collections/1

**Comment by patcon** [comment]
Hard to know where we might want to draw the line in choosing what makes the list... but here are some that came to mind (not prejudging whether any one product is suitable).

Seems like it would be great to involve a legend to indicate when hosted service is an option for running the FOSS software. My understanding is that straddling the line of FOSS + white glove service would be of particular interest.

- https://github.com/placematters-decision-lab/crowdgauge
- https://github.com/pol-is/
- https://github.com/opennorth/citizenbudgetapp.com
- https://github.com/openplans/shareabouts
- https://github.com/tellform/tellform
- https://github.com/consul/consul
- http://tools.dcentproject.eu/
- http://www.nesta.org.uk/publications/digital-democracy-tools-transforming-political-engagement <sup>1</sup>

<sup>1. Might be interesting to steal the categories from this paper, as I'm sure they represent a well-reasoned schema. Could potentially also be applied in an emoji legend format.</sup>

**Comment by patcon** [comment]
- http://blog.openplans.org/2014/12/21299/

**Comment by patcon** [comment]
Actually, this is great: http://www.participatedb.com/about

Maybe there's no need for a new resource? That site leaves quite a bit to be desired (CSS glitches, no advanced search, no machine-readable API)

Perhaps we could instead contact them about making the site code open, and we could improve that resource.

Things that are missing that I'd hoped our hypothetical resource might address (likely in the in-depth spreadsheet portion I referenced above):
- software license
- indicators of activity/interest (github stars, contributor count, open issues, forks, other possible measures of health)
- notable users (somewhat addressed with "projects" type on participateDB)
- categories (for engagement type)
- pricing (for hosted versions)
- space to flagwhen companies have indicated interest in open sourcing (so as to imply a pipeline onto the list for closed source companies)
- anything else?

**Comment by laurawesley** [comment]
Thanks for all the suggestions @patcon  -- I had envisioned a searchable list eventually as well. 

@RMarland reminded me of Participedia: http://participedia.net/en I'd be tempted to invest my energy there -- it has really detailed and comprehensive set of search criteria...It's also supported by Canadian and American academics, which I think would help with sustainability moving forward. Maybe I could help with some French resources. 

Maybe we could keep this list and focus to the first thing you suggested using the GitHub conventions and just work on building out our library of open source engagement tools by providing ways of surfacing them. Then as we develop case studies, we could cross reference them to Participedia.

**Comment by gabrielcossette-ca** [comment]
Joinup is a very good resource from European Commission on interoperable, digital EU initiatives:

News: https://joinup.ec.europa.eu/news/all
Solutions: https://joinup.ec.europa.eu/interoperability/search
Cases: https://joinup.ec.europa.eu/elibrary/cases

I follow it myself for gov. OSS related news.

**Comment by gabrielcossette-ca** [comment]
Although not specifically geared toward gov. digital engagement, this awesome list is a very good one for OSS Web platforms: https://github.com/Kickball/awesome-selfhosted

**Comment by patcon** [comment]
@laurawesley re: our own list for now, with plan to merge later. great idea!

re: participedia. I went looking for participedia codebase, and seems that as recently as 2 minutes ago, they're building v3 as open source. (Which is really great!)

https://github.com/participedia

cc: @davidascher @dethe (main contributors on v3 project)

**Comment by davidascher** [comment]
Wow, this is interesting.

We'd be very happy to collaborate on the future of participedia. As @patcon mentions, it's all being developed as open source, and we're about to do our first public demo in Montreal tomorrow.

Participedia lists what we call Cases, Methods and Organizations.  This issue seems to be mostly about methods, which is a category which we may need to expand to include "software".   Also happy to explore simply linking to third-party resources.

@dethe and I are the developers on participedia, but there is a group of experts who are probably worth talking to when it comes to adjusting scope.  I'd be happy to connect people offline.

Version française disponible.  A propos, un des buts de Participedia v3 est de faciliter la traduction du site.

**Comment by davidascher** [comment]
For those who may not know. Participedia is a project supported by the Social Sciences and Humanities Research Council of Canada (SSHRC). SSHRC funding was provided in April 2011 in the form of a two-year Partnership Development Grant. Participedia was also awarded a SSHRC Partnership Grant for five years beginning in April 2015.  Participedia is a global community of researchers and practitioners hoping to catalogue and compare the performance of participatory political processes around the world.

The current version (version 2) is hosted at https://participedia.net. The next version (version 3) is visible in a beta state at https://participedia.xyz.  This second version is open source and welcome contributions.  We will switch from the former to the latter when it's ready.  Major changes in addition to open source are design changes, usability on mobile, easier to submit simple entries, an API, and more.

**Comment by patcon** [comment]
@davidascher Good luck on the demo tomorrow! Is it being livestreamed/recorded, for those who aren't in MTL?

**Comment by davidascher** [comment]
@patcon Thanks.  re: recording, don't know -- I'm not in MTL, our colleagues are doing the presentation.  I'll try to find out.

**Comment by laurawesley** [comment]
This is amazing!! @davidascher would also love to tune into the demo if you can webcast it. 😊

**Comment by MaryBethBaker** [comment]
Archiving this thread.

**Comment by pragmaticplay169** [comment]
[Game Pragmatic Play](https://188.166.226.169:9999/) merupakan permainan slot online yang terkenal dan terbaik di seluruh asia
