### ISSUE TITLE
Public Engagement Case Studies on Participedia /  Etudes de cas d'engagement public sur Participedia

### ISSUE THREAD

**Issue by inthedistance** [canada-ca/welcome#23]
The Public Engagement and Consultations team at Privy Council Office is working on a pilot project.

We want to establish indicators to define a success criteria for public engagement and consultation. 

We want to answer the question: what does good public engagement and consultation look like?

**We want to inspire and connect people by showing what worked well** 

**Objectives of the project:**

- To collect 12-15 case studies on public engagement and consultation conducted by the Government of Canada. 
- Show the processes, tools and resources available to conduct public engagement and consultation projects.
- To contribute to the growing open source library of public engagement and consultation case studies at [Participedia](https://www.participedia.net/). 

(ongoing iteration of objectives)
 
We love the [Participedia ](https://www.participedia.net/)model (conversation started on github [here](https://github.com/canada-ca/welcome/issues/20) and would like to know more about how we can use it as an avenue to share the case studies for the pilot.

**Comment by inthedistance** [comment]
Taken from our initial conversations with Participedia -  

**A few things we are interested in knowing:**

- The data model for all the consultation metadata (displayed on the right hand side of the case/methods pages), and the data model for the main content

-  Ways we can add or adjust the content sections to include other types of content such as icons, diagrams, links, etc.

- How can we improve the look and feel of the pages to provide better visual clarity for the readers?

-  API and other ways of sharing and comparing consultation projects

**Comment by inthedistance** [comment]
**posted by Patrick**

Hi Luisa! This is an exciting email to receive! Unfortunately, I'm quite busy today, and so unable to join a call. (Oddly enough, I'm aactually meeting with members of [Etalab](https://techcrunch.com/2014/02/12/how-frances-open-data-team-is-modernizing-the-french-government-through-data/) in NYC, in regards to [Pol.is](http://participedia.net/en/methods/polis) :)
 
Having said that, I'm not participating in Participedia at all, and so I'm probably the participant with the least information to share :)
 
But, given that the v3 source code is public, I looked into a few of your questions. (Keep in mind that this is the upcoming v3, NOT the current website at [participedia.net](http://participedia.net)!)
 
- re: data models cases and "main" content (presumably you mean "methods"?) can probably be gleaned from the test data hosted in the source code: (https://github.com/participedia/api/blob/master/migrations) (for example, cases.csv and case_something.csv)
- re: API. New site appears to use an open standard for APIs. This means the API comes with free and pretty documention, that will look a lot like this: https://swagger.io/swagger-ui/ If you can get a developer to run through the build process for this [code repository](https://github.com/participedia/api) (and host it somewhere for test), then you should be able to explore their API from the browser.
- re: improve visual look. I would imagine this would require having a visual designer on staff to contribute to the public codebase. But I'll let the project maintainers speak for themselves on this :)
 
Question for the maintainers -- would it be possible to host a demo version of the upcoming v3 participedia somewhere like [beta.participedia.net](http://beta.participedia.net)? That might allow more stakeholders (particularly those with less technical skills) to contribute meaningfully in the GitHub issue queue in regards to decisions you're making for v3.
 
Anyhow, keep me posted on your call! If, for this meeting, you felt like testing out a variation of the Taiwanese Digital Minister [Audrey Tang's principles on communication transparency](https://talk.pdis.nat.gov.tw/t/principles-for-handling-official-visits-to-digital-minister-audrey-tang/70), then I would definitely listen/watch/read afterward ;)

**Comment by luluissaa** [comment]
@patcon @davidascher Let's shift the conversation here. Please feel free to loop in others who you think may be interested in getting this pilot off the ground. 

Having a nicely documented API really opens up the opportunity for content on Participedia to be shared to other websites beyond the current pilot. It also makes curating content for different audience segments much easier, considering the fact that practitioners are not the ones who need to access these case studies. It is important to also show the potential of this pilot in relation to the larger site. Thoughts on how do we demonstrate the pilot as an MVP?

The staging site for v3 looks stunning! 

I am very interested in hearing Pol.is 's experience of visualizing topic responses distributions for the participants to help people understand the landscape. Maybe it can help our team to develop more informative visual cues to illustrate where a particular case study fits in the overall consultation process.

Also Thanks @inthedistance for setting up this thread :) 

Cheers,
Luisa

**Comment by davidascher** [comment]
A few comments on some of the specific points brought up in https://github.com/canada-ca/welcome/issues/23#issuecomment-331490523 

a) the data model for participedia is under review, as the original model had a bunch of problems both from a data rigor point of view as well as various other concerns.  I would encourage focusing for this pilot on things that don't require knowing the final data model, as it's likely to hold up progress.  The balance we're looking for is a model that is light enough that broader audiences both understand it and are willing to submit data, but not so light that it precludes quantitative analyses in the long term.  The v2 model is currently rich enough that in practice only active participants in the project are contributing data, and even for that restricted audience there are the usual taxonomical debates.

b) The content area currently (and when I say currently I always mean the v3 site which isn't the official site yet) supports the usual rich text markup, including links. We can add support to uploading inline images in a later release, but it does also support adding images and links to videos as metadata on the case/method/organization.

c) The look and feel in v3 is obviously different (and we think, better).  Let us know if you have specific suggestions, but in general we'd rather have a consistent design approach for all cases/methods/orgs for the data seen via the participedia site (obviously other sites using the same data can display it however they want)

d) the API for participedia v3 is self-discoverable at https://api.participedia.xyz/.  There are likely bugs in the API documentation, and if you find them please file them.

In general, for participedia v3's implementation, we encourage bug reports on https://github.com/participedia/frontend/issues for issues having to do with the front-end and data issues, and https://github.com/participedia/api/issues for issues having to do with the API server.

**Comment by jesicarson** [comment]
Hi all,
I'm Jesi Carson, Participedia's Design and Communities Coordinator. 
Anyone interested in joining the Participedia slack team, feel free to get in touch with me by email at info@participedia.net and I'll send you an invite. 
Anyone interested in joining a Skype call to discuss this project, please participate in this Doodle Poll: https://doodle.com/poll/qxs6wqturgz28mra (Please include your Skype name in the poll so I can add you to the call. All times listed in PST.)
Anything else, feel free to reach out. 
Cheers,
Jesi

**Comment by inthedistance** [comment]
@jesicarson Hi Jesi, great to meet you! Thanks for the invite to slack, I will send an email. I would definitely be interested in discussing the project as I am sure my director @laurawesley and our colleague @luluissaa would also like to join the call. I will check our schedule's tomorrow and fill out the doodle pool. Really looking forward to the discussion!

**Comment by jesicarson** [comment]
Looks like the call (google hangout) is booked for Monday, October 2nd from 12pm-1pm PST. 
[Join the hangout here](https://hangouts.google.com/hangouts/_/uoa3rzrysvau7jghrha2jebziie).

**Comment by plscully** [comment]
Hi, all – I’ve taken the liberty of preparing a draft agenda for our Oct 2nd call. Please feel free to suggest changes. I am happy to help facilitate the call from our side, and invite one or more of you to guide us through PCO’s part of the discussion.

Earlier in the github thread the PCO team requested “the data model for all the consultation metadata (displayed on the right hand side of the case/methods pages), and the data model for the main content”. The best way to see the current data model is to register on participedia.net and select “edit” for one of the cases. Then scroll down a bit until you see a row of tabs (overview, location, media, purpose, etc). Selecting these tabs allows you to see the questions & responses that generate the data displayed on the right-hand side of each case. The data model for “methods” can be viewed using a similar approach.

As David noted, we are currently revising our data models. The data model for cases is 95% done and we hope to add it to the xyz site within a few weeks. In the meantime, we are about to begin revisions on the data model for methods. Changes in the two data models will not be radical. We are simply trying to create a framework that accommodates a wider range of “real world” political contexts, while also making transparent the assumptions behind the models.

Best, - pat
 * * * * * * * * * * * *
**DRAFT Agenda**
1. Introductions
2. PCO elaborates on their stated objectives, e.g., how expansive a range do you want to feature of “goals, process, tools and resources available to people for public engagement and consultation projects”?
3. PCO shares its sense of the ways in which the Participedia data and platform can help them meet their project objectives.
4. Participedia provides updates on status of its v3 implementation, including the new platform and data model.
5. Identify potential next steps.

**Comment by inthedistance** [comment]
Thank you Peter for preparing this - looking forward to speaking to everyone today.

**Comment by inthedistance** [comment]
An update from the meeting on 10/2/2017 that
@davidascher @plscully and @jesicarson and I had on Participedia and the Privy Council Office Case studies project. 

- Discussed ongoing collaboration in terms of a mutual shared interest in producing high quality case studies that create indicators to define a success criteria for public consultation. 

- Participedia will share designs and data model as they become available to support our case studies.

- Timeline for Participedia to launch [new version of the site](https://participedia.xyz/ ) is aiming for early next year, with user testing currently underway. This aligns well with our intended timeline of completing case studies in the new year. 

Looking forward to continuing the discussion!

**Comment by plscully** [comment]
@inthedistance Thank you for this summary, which aligns with our sense of the meeting.
 
Per your question as to whether any other governmental agencies are working with us in a way similar to what PCO envisions, here are some examples of cases developed in partnership with the World Bank's Governance Global Practice, in which two the Bank’s Kenyan field consultants used Participedia’s data model to document examples of participatory budgeting in [Makueni ](http://participedia.net/en/cases/makueni-county-participatory-budgeting-fy201516)and [West Pokot ](http://participedia.net/en/cases/west-pokot-county-participatory-budget-hearings-kenya)Counties.

And here is an example of a case developed in partnership with the "[Tuscan Regional Authority for the Guarantee and Promotion of Participation](https://www.google.com/search?q=partecipazione%40consiglio.regione.toscana.it&oq=partecipazione%40consiglio.regione.toscana.it&aqs=chrome..69i57j69i58.382j0j8&sourceid=chrome&ie=UTF-8)" by Participedia research assistants at the[ University of Coimbra's Centre of Social Studies ](http://www.uc.pt/en/iii/linksMembros/CES-s)(Portugal). This case focused on [redevelopment of Florence's airport](http://participedia.net/en/cases/airport-lets-talk-about-it-aeroporto-parliamone-tuscany-italy). It still needs a bit of editing, but I've included it here to give you a sense of the range of types of projects that Participedia is documenting.

Also please note that we will be happy to identify one or more student research assistants working on our SSHRC Partnership Grant who, if you like, could help PCO develop your cases.

**Comment by laurawesley** [comment]
I'm so excited to see this take shape!! Thanks all!

**Comment by inthedistance** [comment]
@plscully and @jesicarson Hope all is well, quick question - do you think it is best that I begin inputting case studies into the new Participedia website or the old version?

**Comment by jesicarson** [comment]
@inthedistance Please use participedia.net for now. We're still in the user testing phase of participedia.xyz, and the data forms will soon be updated. @plscully will let us know when we can share the updated data model.

**Comment by inthedistance** [comment]
@jesicarson thank you. I will use the old site for now!

**Comment by inthedistance** [comment]
@jesicarson @plscully - Hi all, hope everything is well. As I progress further into the case studies I am refining my methodology. I am wondering, can I get a list of all possible fields for the purpose and process category? I am trying to create some common terms and want to map the options on participedia back to the interview questions and an engagement template we are working on. Thank you!
![data fields for purpose](https://user-images.githubusercontent.com/15850985/31908110-d949b7da-b803-11e7-85fc-a48cdc21ee18.PNG)

**Comment by plscully** [comment]
@inthedistance @jesicarson - Hi! I will send you links via email to strong drafts of the new purpose and process fields. We'd rather not do a public posting of draft data model. 

Two of the biggest design questions we are working through as we finalize these are (1) how to re-structure things so that users don't select a large number of responses for any given question. We've learned that doing so on the current site makes it very difficult for analysts to make sense of the information, so we need to implement some sort of priority setting mechanism. And (2) relates to how to capture & code cases that include multiple components, each of which may have different purposes and process elements.

I will also send you a link to some guidelines that many users have found useful.

**Comment by laurawesley** [comment]
I wonder if we should be crowdsourcing all the possible objectives. That's a really critical search criteria.

**Comment by inthedistance** [comment]
@plscully Thank you for sending the information to me. @laurawesley I completely agree. I want to get an idea of what we have first, then we can start reaching out!

**Comment by plscully** [comment]
@laurawesley If I understand you correctly, your concern is that providing a restricted list of options under "purpose" and other categories -- what we refer to internally as the "fixed fields" -- will limit our crowd sourcing capacity. We are trying to strike a middle ground by combining the limited options presented in the data forms with the open, searchable text allowed in each case's narrative section. We also give users the ability to suggest new options. We will catalog & review all suggestions for new options as they arrive, periodically updating the data fields as necessary. 

Also, please keep in mind that users can use other categories such as issues/topics and participant recruitment strategies/tactics to help define each case's purpose.

I have attached a 2016 paper by two members of our team that helped inform design of our new data model. Among other insights, it explains how providing too many options actually reduces Participedia's explanatory power. 
[Report on Improving Participedia Data Collecting Capabilities_May 2016.pdf](https://github.com/canada-ca/welcome/files/1411073/Report.on.Improving.Participedia.Data.Collecting.Capabilities_May.2016.pdf)

**Comment by inthedistance** [comment]
@plscully Thank you for attaching that paper!

**Comment by laurawesley** [comment]
No, I'm not concerned about the limited number, I agree it should be fixed fields. I also understand combining search terms @plscully.

My interest is in understanding how others define their objectives so we can get the best short list possible. 

I was speaking to Tim Hughes from Involve UK. He said to check out their site for more case studies.

**Comment by laurawesley** [comment]
Another side / related initiative is a decision tree to help policy and comms analysts choose engagement methods and tools, which is why I'm interested in objectives.

**Comment by laurawesley** [comment]
PS. I love that users will be able to suggest new categories @plscully

**Comment by inthedistance** [comment]
@plscully Interviews and case studies are well underway on our end. I will have some things to share next week including, suggestions for common vocabulary and a list of objectives around case study submissions from policy and comms perspective. @laurawesley has made suggestions above. This common vocabulary and objectives list will also help refine Participedia case study submissions. We have been crafting this as we build out a decision tree to help policy and comms analysts choose engagement methods and tools.

**Comment by plscully** [comment]
@inthedistance @laurawesley This all sounds excellent! We’re eager to see what you’re developing. Regarding a decision tree, this is something we’ve also been interested in as a way of facilitating the ability of participation practitioners to identify the methods and tools that are most appropriate for their situation.

One of our project collaborators, Matt Leighninger (Director, Yankelovich Center for Public Judgment), developed a rudimentary site called the “Democracy Helpline” back around 2005 when he was directing the Deliberative Democracy Consortium. The helpline posed diagnostic questions to help users think through the design choices of their public involvement projects. Using the answers to the questions, the site would then offer a set of publications, organizations, and program examples that matched their needs and interests. Unfortunately, Matt was unable to raise funds to flesh out the helpline, so it no longer exists. However, Matt still has all its raw text and [this link that shows what one of the key pages looked like](file:///C:/Users/Patrick%20Scully/AppData/Local/Microsoft/Windows/INetCache/Content.Outlook/SE6DFDMJ/Democracy%20Helpline%20-%20Welcome.htm). 

Participedia has not discussed recently whether this is the type of function we would like to build, but it’s something our executive committee and partners will want to consider down the road. A helpline of this sort may be more than you have in mind as the PCO fleshes out your decision tree, but it seemed worth mentioning.

**Comment by patcon** [comment]
cc Denis Carr

**Comment by laurawesley** [comment]
Oooo really?! Good to know would welcome collaborators! @plscully

**Comment by inthedistance** [comment]
Hi @patcon @jesicarson @davidascher - hope all is well. I am almost ready to release the first iteration of our website that features the case studies and other projects we are working on at PCO. I checked the terms and conditions of the Participedia logo - would you be comfortable with us displaying it on our website? We want to be able to show our collaboration with you and point people to Participedia.  I will be sending an invite for a follow up discussion/brainstorm once you get a chance to see the new site. I will post it here once it's ready.

**Comment by jesicarson** [comment]
Hi @inthedistance ,
You are welcome to display our logo. In the interim of launching the new site, we're using a simplified black logo. You can download the interim graphics package for Participedia [here](https://drive.google.com/open?id=0B5j_dGoSFCLJTERVY1FtaWZjMlU).

**Comment by inthedistance** [comment]
Thank you @jesicarson !

**Comment by inthedistance** [comment]
@jesicarson - do you have a French version of this graphic? If not, can we translate it? 
![participedia1](https://user-images.githubusercontent.com/15850985/33213797-1b2893a4-d0f7-11e7-9573-a75723a80e9e.PNG)

**Comment by plscully** [comment]
@inthedistance  @jesicarson Jesi can say for sure, but I am almost positive that we do not yet have a French version of this, so please feel free to translate it. BTW, if you like, you could increase the number of users to 2600+ and of cases to 750+ . And although the website says we have many more methods and organization entries, its best to leave them at the numbers in this chart because we will be culling many of the entries in those last two sections.

**Comment by inthedistance** [comment]
@plscully Thank you! I will be in touch next week.

**Comment by jesicarson** [comment]
@plscully @inthedistance I can update the graphic with the new numbers and the french translation if it is provided. It was made with InDesign.

**Comment by inthedistance** [comment]
@jesicarson I am waiting on French translation. Then I will post it here for you. Thank you!

**Comment by jgroenen** [comment]
Hi all, I am working on a small open source project listing curated sets of use cases/projects/case studies: https://clarity.codefor.nl it runs on top of an api https://cbase.codefor.nl

Next step would be to make it interoperable with other such platforms, by 1) collecting the set of all platforms for sharing projects/use cases/case studies: https://clarity.codefor.nl/cbase/project-repositories-50219f7e 2) checking out their data formats (and possibly api's) 3) defining an exchange format that matches up with 90% of the data formats 4) develop proxy services for the platforms (that scrape or query their content and transform into data exchange format) 5) build central search interface (and also offer api to the decentralized platforms)

Would love your feedback.

**Comment by inthedistance** [comment]
@jesicarson Here is the French translation for the graphic - any chance you could update it and provide me with both a new English and French version? Thank you!

Participedia | Participedia
-- | --
www.participedia.net | www.participedia.net
info@participedia.net | info@participedia.net
150+ Team Members | Équipe de plus de 150 membres
30+ Partner Organizations | Plus de 30 organisations partenaires
15+ Countries | Plus de 15 pays
Anyone can join the   Participedia community and help us to crowdsource, catalogue and compare   participatory political processes around the world. | Toute personne peut se joindre à la communauté   Participedia et nous aider à collecter, à répertorier et à comparer les   processus politiques participatifs partout dans le monde.
Explore: Gain insight from a   growing database of Democratic Innovations. | Explorez : Obtenez des points de vue à partir   d’une base de données croissante sur les innovations démocratiques.
Create: Edit existing content   or publish your own under the Creative Commons. | Créez : Modifiez le contenu actuel ou publiez   le vôtre dans le cadre de Creative Commons.
Teach: Engage students and   showcase their research on a collaborative platform. | Enseignez : Mobilisez les étudiants et   présentez leurs recherches sur une plateforme axée sur la collaboration.
2300+ Users | Plus de 2 300 utilisateurs
650+ Cases | Plus de 650 cas
450+ Organizations | Plus de 450 organisations
150+ Methods | Plus de 150 méthodes

**Comment by dethe** [comment]
@jgroenen The Participedia data is licensed under the Creative Commons (https://participedia.net/en/legal), so it is open for reuse under those terms. We are in the process of releasing a big update to the site which will change the APIs, which will continue to be open. I will be updating out documentation of the APIs and making examples, but right now we are focused on getting the new site finished and in production, so that may take some time. I am happy to answer questions about the APIs and data models in the meanwhile: dethe@livingcode.org

**Comment by inthedistance** [comment]
@dethe Thank you for the update!

**Comment by jesicarson** [comment]
@inthedistance updated english and french versions of the Participedia info graphic handout: 

[Info Graphic Handout_8.5x11_12-08-17 ENGLISH.pdf](https://github.com/canada-ca/welcome/files/1543646/Info.Graphic.Handout_8.5x11_12-08-17.ENGLISH.pdf)

[Info Graphic Handout_8.5x11_12-08-17 FRENCH.pdf](https://github.com/canada-ca/welcome/files/1543647/Info.Graphic.Handout_8.5x11_12-08-17.FRENCH.pdf)

**Comment by inthedistance** [comment]
thanks @jesicarson I will send you and @plscully a link to the site we have been working on next week and set up a call. Have a great weekend.

**Comment by patcon** [comment]
@jesicarson thanks! Would you be in favour of using a public Google Drive folder hierarchy for resources like this that a community might want to have in one place?

In other open organizing groups I work with, we have two non-nested folders to minimize confusion:
- `<Project> - Shared`. Public can view. (Liberal edit access with clear "ask" process.)
- `<Project> - Privileged`. Only invites can view. (Clear "ask" process.)

We also keep a document in public on key resources that are kept private, who initiated them, and why they are privileged. This means that even the private resources are legible in general form to everyone, and there is a person who can easily be approached for access :)

I'd be happy to work together on the above if it sounds like it might work for us!

_I created a folder here and invited you as editor, just to demonstrate:_
https://drive.google.com/drive/u/0/folders/1IAmN82zXU39quDnTqioFOsDYJ33uDh4i

**Comment by jesicarson** [comment]
@patcon I'm not opposed to it, just conscious that the interim package I provided in this thread isn't Participedia's final look and feel, and as we lead up to the launch it will likely be adjusted. Maybe we should wait until the launch (early 2018) to announce access to a public folder with updated graphics? @plscully what do you think?

**Comment by patcon** [comment]
Ah, that you for voicing that! I think I understand the need for controlling expectations and deliverables, but I think I did a poor job of explaining and so conflated audiences.

To clarify where I feel something like this might fit: the resources wouldn't be for people interested in final things -- it would be a piece of growing a cfuller ommunity of contributors interested in the same outcomes and steps that your "internal" team cares about -- just as you couldn't operate without access to those resources, a collaborator community (who might be hoped to have a comparable sense of ownership) would probably find those resources to be an important piece as well :)

But I realize I'm perhaps making assumptions about the sort of community that the team has energy to cultivate. I love love love the idea of an open community around the whole effort, larger than just the code. And I'm interested in doing some legwork to help organize, but I can't offer that (or even propose how it might work) without public access to raw information resources, which might be earlier materials than traditionally imagined audiences might expect :)

**Comment by plscully** [comment]
@patcon @jesicarson Hi Pat – Thank you for encouraging us to think about additional ways we can open-up our content to increase participation and ownership in Participedia. Other than for a few types of content such as lists of potential cases that users might want to contribute, we haven’t yet given serious thought to the type of cataloguing you’re suggesting. As things now stand, just about everything in our google files is open to the 100+ people who form the core group working on our SSHRC grant, but as you suggest, we can & probably should make much of this open to many more people. 

I would like to take you up on your generous offer to help us with this, but I’d like to delay work on it for a few more months. We are behind on a few important deadlines – most of which are related to building our new website and rolling out a communications/engagement campaign – so we need to keep new projects to a minimum. In fact, after seeing your folder I changed the permissions to “specific people” for some of the docs you identified. I doubt that we would receive many comments if we left them open, but given everything we have on our plates, I’d rather not risk having to respond to unsolicited input right now.

In the meantime, if you have examples of how other projects have shared this type of data (that is, info other than code), we’d love to see them. I’m especially interested in the strategies that inform different approaches to sharing what many people might consider to be “insider” information.

**Comment by patcon** [comment]
Yay! Grateful to hear that y'all at Team Participedia might be open to it down the road :)

As for how to expose these sorts of deep resources -- we've recently been using Trello as a project dashboard of sorts, for a few open projects I'm involved with:

- [g0v.network](https://trello.com/b/ZzxRte37/g0vnetwork-task-tracker): building a citizen-led consultation community and process, inspired by vTaiwan.
- [Civic Tech Toronto organizers](https://trello.com/b/tLfJChM2/operations-tasks): coordinating our hacknights and longer-term projects.

**Comment by inthedistance** [comment]
@plscully @jesicarson - Happy new year! Do you have time for a quick call this week? I was inputting some test case study data in the new site to test it out. It helped me think through a few things. I have some questions about data fields and the data model. Let me know when your free. Thank you!

**Comment by jesicarson** [comment]
@inthedistance Sure, I could do a call this Thursday after 12pm PST or anytime Friday. 
I should mention that the data model on Participedia.xyz has not yet been updated to reflect the drafts that Pat shared with you. We’re aiming to have them updated live on xyz by mid-January. 
At any rate, happy to chat!

**Comment by plscully** [comment]
I am also happy to discuss this in a call. My schedule is open from this Thursday 12pm to 3pm PST or anytime on Friday.

**Comment by inthedistance** [comment]
@plscully @jesicarson I will send an invite for Thursday between 12-3pm PST. Looking forward to catching up. I will send some points of discussion and possibly some links to a few working documents/case studies.

**Comment by inthedistance** [comment]
@jesicarson @plscully I sent the invite for tomorrow for Google Hangouts. Let me know if you received it. I scheduled it for 3:00-3:30 EST for the equivalent of 12:00 PST. Hope that works!

**Comment by plscully** [comment]
@inthedistance Got it!

**Comment by inthedistance** [comment]
@jesicarson @patcon started issue thread for decision tree - see above and [Google folder](https://drive.google.com/drive/folders/1Ep8BY1PdtYdn5SjcnpTu5TqmhpiQCIiA?usp=sharing). Feel free to put anything in there. I will be adding the mapping I was working on and other documents soon enough.

**Comment by Mikecamero** [comment]
Hi! @inthedistance suggested that I post this research on public engagement goals here. @plscully this is the draft paper I sent you last month. Thanks for any feedback! [](https://drive.google.com/file/d/1z-tbqqGZPM5M7XlVRlR3etXo_6k9CCIE/view?usp=sharing)

**Comment by MaryBethBaker** [comment]
Archiving this thread case studies have been added to Participedia spring 2020 - government of Canada collection. They can also be found on gcwiki: https://wiki.gccollab.ca/Public_Engagement_Case_Studies

**Comment by jesicarson** [comment]
Thanks @MaryBethBaker! We're very excited to have a [Government of Canada collection on Participedia](https://participedia.net/collection/6493) as a result of this collaboration. It's also great to be mentioned on gcwiki, thanks :) 
If anyone is interested, we're organizing a Participedia Data Design Jam on Github too, please join us: https://github.com/participedia/api/issues/895
Keep in touch!
