### ISSUE TITLE
Principes numériques du gouvernement du Canada (GC) / GC Digital Principles

### ISSUE THREAD

**Issue by OpenGovCan** [canada-ca/welcome#24]
Nous développons un ensemble de principes pour guider le développement numérique dans le gouvernement du Canada. Cet ensemble formera la façon dont nous abordons la gestion de nos renseignements, nos technologies et la prestation des services. Nous nous sommes basés sur les pratiques exemplaires internationales et nous cherchons de la rétroaction. 

Du 26 octobre au 8 decembre, vous aurez l’opportunité de commenter notre ébauche des différents principes. Quoique nous reconnaissons que ces principes ne seront jamais coulés dans le béton, mais évoluerons avec le temps alors que le contexte change, nous sommes assidus pour votre rétroaction afin que nous puissions aller de l’avant avec une version que nous pouvons mettre en pratique. 

# Principes numériques

## 1.	Comprendre les utilisateurs et leurs besoins
Commencer avec les besoins des utilisateurs et ensuite construire pour eux et avec eux. Mener des essais continus avec les utilisateurs. Faire le travail difficile afin qu’ils ne soient pas obligés de le faire.

## 2.	Effectuer constamment des itérations et des améliorations 
Développement agile au moyen des phases alpha, bêta et réelles. Effectuer des essais de bout en bout et apporter sans cesse des améliorations en réponse à la rétroaction des utilisateurs. Faire des essais le plus tôt et le plus souvent possible.

## 3.	Bâtir la bonne équipe
Mettre sur pied et habiliter des équipes multidisciplinaires, en établissant des liens entre stratégie et exécution.

## 4.	Développer une culture orientée vers le service
Diriger une équipe et mettre en œuvre une culture ministérielle axée sur les utilisateurs.

## 5.	Travailler dans un environnement ouvert
Échanger et collaborer dans un environnement ouvert, élaborer des plans pour faire en sorte que les données sont ouvertes dès le début.

## 6.	Intégrer, de façon équilibrée, la sécurité et la protection des renseignements dès le début 
Considérer le contexte opérationnel. Gérer les risques.

## 7.	Créer de façon ouverte et interopérable
Considérer également les sources libres. Utiliser des normes ouvertes. Créer de façon interopérable et songer à ce qui peut être réutilisé.

## 8.	Utiliser les bons outils pour le travail
Utiliser les solutions et les plateformes gouvernementales communes. Construire l’informatique en nuage d’abord.

## 9.	Concevoir et fournir des services transparents et éthiques
Faire preuve d’ouverture et de transparence dans l’utilisation des systèmes automatisés et respecter les lignes directrices en matière d’éthique.

## 10.	 Être inclusif et offrir du soutien pour ceux qui en ont besoin
Favoriser un environnement inclusif, les langues officielles et l’accessibilité dans la conception. 

## 11.	 Connaître vos données
Gérer les données conformément aux normes. Mettre en œuvre des outils analytiques et utiliser les données recueillies.

## 12.	 Être responsable envers les Canadiens
Définir les paramètres du rendement axé sur les utilisateurs. Publier des données en temps réel.

## 13.	 Développer des partenariats ouverts et innovateurs
Reconnaître qu’une organisation ne peut pas avoir toutes les meilleures idées. Créer des partenariats et collaborer.

## 4.	 Dépenser l’argent judicieusement
Signer des contrats de façon sensée et respecter les normes d’approvisionnement. 

## 15.	Faire l’essai des services avec le sous-ministre ou le ministre
Faire l’essai de tous les services destinés au public avec le sous-ministre ou le ministre responsable.

___

We are developing a set of principles to guide digital development in the Government of Canada. These will shape how we manage our information, our technology, and provide services. We have based these on international best practices and we’re looking for feedback. 

From October 26 until December 8, 2017, you will have the opportunity to comment on our draft set of principles. While we recognise that these won’t ever be set in stone, but will evolve over time as the context changes, we are keen to get your input so that we can quickly move to a version we can test in practice. 

# Digital Principles
## 1.	Understand users and their needs
Start with user needs and build for them, and with them. Conduct ongoing testing with users. Do the hard work so that they don’t have to.

## 2.	Iterate and improve frequently
Develop in an agile manner using alpha, beta and live phases. Test end-to-end and continuously improve in response to user feedback. Test early and often.

## 3.	Build the right team
Create and empower multidisciplinary teams, linking policy with delivery.

## 4.	Build a service-oriented culture
Lead and implement a team and departmental culture focused on users.

## 5.	Work in the open
Share and collaborate in the open, plan to make data open from the start.

## 6.	Integrate proportionate security and privacy from the outset 
Consider business context. Manage risks.

## 7.	Build in an open and interoperable way
Give equal consideration for open source. Use open standards. Build in an interoperable and reusable way.

## 8.	Use the right tools for the job
Use common government solutions and platforms. Build cloud first.

## 9.	Design and deliver transparent and ethical services
Be open and transparent in the use of automated systems and comply with ethical guidelines.

## 10.	 Be inclusive and provide support for those who need it
Build in inclusiveness, official languages, and accessibility by design. 

## 11.	 Know your data
Manage data in line with standards. Implement analytical tools and use the data you collect.

## 12.	 Be accountable to Canadians
Define user-centred performance metrics. Publish real time data.

## 13.	 Develop open and innovative partnerships
Recognize that an organization can’t have all the best ideas. Create partnerships and collaborate.

## 14.	 Spend money wisely 
Enter into sensible contracts and comply with procurement standards. 

## 15.	Test services with the Deputy Minister and/or Minister
Test all new public-facing services with the Deputy Minister and/or Minister responsible.

**Comment by patcon** [comment]
Would there be room for something that gets at this:

"If you can't find political capital to run an experiment internally, be of service to citizens who might be eager to run a comparable experiment externally"

(I realize it's a little awkward to phrase, but I see this tacitly being condoned all the time by civil servants, and would be interesting to consider how it might be codified.)

**Comment by chrismajewski** [comment]
Is this based off the UK version?  It looks similar.

https://www.gov.uk/service-manual/service-standard

We've been proposing it at Stats as a means to define a departmentally blessed consistent development standard, 3rd party support in conflict and address some boundary creep.  IT transformation is afoot at Stats, I'll keep pressing for something simlar be adopted here.

I believe the UK version is supported by a 3rd party audit platform to encourage compliance.  Not a bad idea even if they don't.

@MaryBethBaker is this something actionable at a GC level?  As a report card it would have to be done in a reporting chain but maybe we can help define what a Canadian version looks like for good citizen developer's best practice.  A Mni-Manifesto of sorts.

**Comment by patcon** [comment]
@chrismajewski nice. if this _is_ based off the UK Digital Service Standard, I would suggest we treat it more like standard and lock down the same lingo. Keep things [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself), that is :)

Perhaps we could coordinate with UK service manual to actually version the standard, so that it can evolve in a manageable way, and be inherited fully or in part by other governments (or different levels of gov)

**Comment by xander-gds** [comment]
@patcon Sorry for the delay. I'm on the team who look after the current UK standard. It's really good to see this!

We're currently working on an [update to the standard](https://gds.blog.gov.uk/2017/09/27/help-us-update-the-service-standard/) which you might find interesting.

There's a lot to be said for international collaboration on better service design - you might be interested in the [International Design in Government Community](https://groups.google.com/a/digital.cabinet-office.gov.uk/forum/#!forum/international-govdesign).

As @chrismajewski mentioned, most UK digital service teams are required by Cabinet Office (our central department) to have their services assessed against the standard by an assessment panel from either the Government Digital Service or their own department, depending on the size of the service.

A few things occur to me as especially important if you were to enforce a standard. I think they would make a tight coupling of a service standard across national boundaries quite tricky.

What's expected of teams needs to be quite clear. For example, "Build the right team: Create and empower multidisciplinary teams, linking policy with delivery." is an important sentiment concisely expressed, but even with [quite a specific page](https://www.gov.uk/service-manual/service-standard/have-a-multidisciplinary-team) on what we are looking for with our equivalent point, it's still contentious. For example, we hear from teams that it's not always consistently interpreted by assessors. 

The standard needs to be ambitious but achievable for the capability of the teams building the services and the financial/political context they're working in. Once you get specific on how to assess it, I think it would be hard to find an international sweet spot for each point that works for all countries' contexts.

As an example, our planned move from thinking about transactions to thinking about end-to-end services probably would have been an unrealistic ask of service teams back in 2015, even if we'd wanted to include it then.

**Comment by MaryBethBaker** [comment]
Official version of this document online here:
English: https://www.canada.ca/en/government/system/digital-government/government-canada-digital-standards.html
Français: https://www.canada.ca/fr/gouvernement/systeme/gouvernement-numerique/normes-numeriques-gouvernement-canada.html
