### ISSUE TITLE
GC Digital Principles

### ISSUE THREAD

**Issue by digitalnumerique** [canada-ca/welcome#25]
_(Français: https://github.com/canada-ca/welcome/issues/24)_

We are developing a set of principles to guide digital development in the Government of Canada. These will shape how we manage our information, our technology, and provide services. We have based these on international best practices and we’re looking for feedback. 

From October 26 until December 8, 2017, you will have the opportunity to comment on our draft set of principles. While we recognise that these won’t ever be set in stone, but will evolve over time as the context changes, we are keen to get your input so that we can quickly move to a version we can test in practice. 

# Digital Principles
## 1.	Understand users and their needs
Start with user needs and build for them, and with them. Conduct ongoing testing with users. Do the hard work so that they don’t have to.

## 2.	Iterate and improve frequently
Develop in an agile manner using alpha, beta and live phases. Test end-to-end and continuously improve in response to user feedback. Test early and often.

## 3.	Build the right team
Create and empower multidisciplinary teams, linking policy with delivery.

## 4.	Build a service-oriented culture
Lead and implement a team and departmental culture focused on users.

## 5.	Work in the open
Share and collaborate in the open, plan to make data open from the start.

## 6.	Integrate proportionate security and privacy from the outset 
Consider business context. Manage risks.

## 7.	Build in an open and interoperable way
Give equal consideration for open source. Use open standards. Build in an interoperable and reusable way.

## 8.	Use the right tools for the job
Use common government solutions and platforms. Build cloud first.

## 9.	Design and deliver transparent and ethical services
Be open and transparent in the use of automated systems and comply with ethical guidelines.

## 10.	 Be inclusive and provide support for those who need it
Build in inclusiveness, official languages, and accessibility by design. 

## 11.	 Know your data
Manage data in line with standards. Implement analytical tools and use the data you collect.

## 12.	 Be accountable to Canadians
Define user-centred performance metrics. Publish real time data.

## 13.	 Develop open and innovative partnerships
Recognize that an organization can’t have all the best ideas. Create partnerships and collaborate.

## 14.	 Spend money wisely 
Enter into sensible contracts and comply with procurement standards. 

## 15.	Test services with the Deputy Minister and/or Minister
Test all new public-facing services with the Deputy Minister and/or Minister responsible.

**Comment by nschonni** [comment]
Merged content back into #24
