### ISSUE TITLE
Decision Tree Prototype with Participedia

### ISSUE THREAD

**Issue by inthedistance** [canada-ca/welcome#27]
We’ve been working with [Participedia](https://www.participedia.net/) on making GC case studies available on their [new website](https://participedia.xyz/). See [github](https://github.com/canada-ca/welcome/issues/23) conversation for context. 

One of the ways that we want to support policy practitioners, communications analysts, and others who need to undertake engagement is to **prototype a decision tree**. A decision tree is a way to help people understand the context and conditions to make a decision about how and who to engage on open policy making. 

We are inviting collaboration!

**Comment by patcon** [comment]
Cool! In the referenced github issue thread, you mention:

> see above and Google folder

I might be missing something, but I didn't see a Google Drive with relevant info. Would this be a Google Drive that could be linked here? Thanks! :)

**Comment by inthedistance** [comment]
@patcon - Whoops - here is the [google folder](https://drive.google.com/drive/folders/1Ep8BY1PdtYdn5SjcnpTu5TqmhpiQCIiA?usp=sharing) link!

**Comment by MaryBethBaker** [comment]
Archiving this issue.
