### ISSUE TITLE
Help wanted: harvesting urls from open.canada.ca Proactive Disclosure

### ISSUE THREAD

**Issue by YohannaLoucheur** [canada-ca/welcome#28]
Looking for tech help to collect hundreds of url of individual G&C Proactive Disclosures from the open.canada.ca platform and add them to an Excel file that contains the unique ID of each proactive disclosure to match each url.  

It is possible to use the unique ID to search projects on open.canada.ca, so technically we should be able to match ID with url.

Concrete example: 
- pick a project ID from the Excel spreadsheet (eg GC-2017-Q2-0179) 
- search this ID on https://open.canada.ca/en/search/grants and find https://open.canada.ca/en/search/grants/reference/3c63457f551874f066334b370f6c3636 
- copy the url and add it to the GC-2017-Q2-0179 line in the Excel spreadsheet

We need to do this for hundreds of projects, so I'm looking for a way to automate the process. My (not a coder) brain thinks it should be somewhat trivial to tell a computer to look up the ID, copy the url and import it in Excel. But I have no idea how to do it and had no luck with department's IT so far.

Anyone knows how to do this?

**Comment by matthewdarwin** [comment]
I guest a question, why do you want to do this?  What is the benefit?

Alternatively you could just use the ID you already have and build a URL like https://open.canada.ca/en/search/grants?search_api_fulltext=GC-2017-Q2-0179   Albeit this requires clicking an extra link to get the details.

**Comment by YohannaLoucheur** [comment]
Tks Matthew

We include the urls in the data files we publish under the IATI standard (for international development assistance data). This enables data users to go straight to the project disclosure page, from wherever our IATI data is displayed (including our own Project Browser). It counts as "procurement transparency", a key ask from an open government perspective.

We had a system in place to collect the urls when they were published on our own department's website, but with the move to centralize publishing on open.canada.ca our process broke down.

I actually quite like your suggestion, as we could just generate the urls we need both for past disclosures and for going forward.  The extra click isn't too much of an issue, since it takes users to a specific page with unambiguous info. In fact, an added value is that if there are more than one disclosure with the same ID (it does happen, though not very often), they will all show up.

tks!!

**Comment by patcon** [comment]
This might help you, @YohannaLoucheur:
https://scrapinghub.com/portia

(I believe it's designed for non-coders.)

Good luck! :slightly_smiling_face:

**Comment by YohannaLoucheur** [comment]
Turns out the url is based on a formula that uses the reference number (eg GC-2017-Q2-0179). So we'll be able to generate them for both existing and new projects. 
Now we just need to find a way to import them into the SAP MM module...  

Thanks everyone!
