### ISSUE TITLE
Design System for Canadian Government

### ISSUE THREAD

**Issue by Paquette** [canada-ca/welcome#31]
I have always had a very difficult time navigating any aspect of the Canadian Government websites. I recognize that it utilizes bootstrap and bringing a project from concept to completion requires a lot of logistics, legal requirements and changing scopes so doing anything gracefully is lately unheard of.

I'd love to see a structured design system come from an Open-Source initiative on this org and see if it goes anywhere. It's something I spend a great deal of time working on and can (and am quite interested) in contributing to. I don't have a preference of what technology or constraints would have to be worked within. I'm just extremely keen on helping Canadians have an easier time finding resources and portals to services they need.

With the websites having a _lot_ of text to read I'd want to focus a lot on the research that's been made about readability. I've also dedicated my career focus to working with building some accessibility libraries so I feel like my learnings over the next while will be beneficial as well.

Working at a Government capacity would be very cool, however I completely understand if it's not something that is in the playbook at the moment.

To be clear, I'm looking at having a bunch of contributors help build out some reusable components that would be easy for the future development or upgrading of government-operated websites, web systems and internal tools to leverage.

**Comment by nschonni** [comment]
The UI system for government websites is actually https://github.com/wet-boew/wet-boew, although Bootstrap is used as a base in the project.

**Comment by Paquette** [comment]
Awesome! Good to see it's already a thing! I'll move over to there instead then.
