### ISSUE TITLE
Call for ideas on Digital Policy / Appelez pour des idées sur la politique numérique

### ISSUE THREAD

**Issue by SonyaRead** [canada-ca/welcome#32]
The Treasury Board Secretariat is developing a Digital Policy and is looking for your input. Full details and backgrounder on our GCcollab group Digital-Numerique. https://gccollab.ca/groups/profile/588431/digital-numerique 
Le Secrétariat du Conseil du Trésor du Canada souhaite élaborer une politique sur le numérique et chercher votre collaboration. Tous les détails et document d'information sur notre groupe GCcollab Digital-Numerique https://gccollab.ca/groups/profile/588431/digital-numerique

**Comment by MaryBethBaker** [comment]
Archiving this issue.
