### ISSUE TITLE
Digital Policy Online Consultation – June 11 to June 14 / Consultation en ligne portant sur la Politique sur le numérique – 11 au 14 juin

### ISSUE THREAD

**Issue by SonyaRead** [canada-ca/welcome#34]
(La version française suit.)

We have held a number of in-person workshops with federal departments as part of the development of a single Digital Policy to amalgamate and evolve the Treasury Board administrative policies on service, information technology, and information management, and components of cyber-security. 

We have collated the broad range of feedback into high-level emerging themes. And, we would invite you to participate in a very brief, anonymous [online questionnaire](https://questionnaire.simplesurvey.com/f/l/dpc-cpn?idlang=EN) to help us further refine, validate and prioritize what we are hearing. This also offers an opportunity to provide further comments. 

The online questionnaire is available between Monday, June 11th and Thursday, June 14th. We would encourage you to share this invitation broadly with your departmental colleagues. 

Thank you for your continued support in the development of a Government of Canada Digital Policy. 

---

Nous avons organisé plusieurs ateliers en personne avec les ministères dans le cadre de l’élaboration d’une Politique sur le numérique unique visant à fusionner et à faire progresser les politiques administratives du Conseil du Trésor au chapitre des services, de la technologie de l’information et de la gestion de l’information. 

Nous avons divisé le large éventail de commentaires en fonction des thèmes émergents et importants. De plus, nous vous invitons à remplir un [questionnaire en ligne](https://questionnaire.simplesurvey.com/f/l/dpc-cpn?idlang=FR) très bref et de façon anonyme pour nous aider à améliorer et à valider les commentaires reçus, puis à les classer en ordre de priorité. Ce questionnaire vous offre également l’occasion de fournir d’autres commentaires.

Le questionnaire en ligne sera disponible du lundi 11 juin au jeudi 14 juin. Nous vous encourageons à transmettre cette invitation aux employés de votre ministère. 

Je vous remercie de votre soutien continu quant à l’élaboration d’une Politique sur le numérique du gouvernement du Canada.

EDIT:

Please note, the IDEAS stage of Phase 1 is now complete. Thank you for your interest. We will be using the feedback and input received across all our outreach channels to explore potential directions for the Digital Policy. We will be reporting back here in the coming weeks to seek your views.
In the meantime, we always welcome your input if you have something to share. You can provide your comments in the Discussion section of our GCcollab group.

Veuillez noter que l'étape IDEAS de la phase 1 est maintenant complétée. Merci pour votre intérêt. Nous utiliserons les commentaires reçus pour explorer les orientations possibles de la politique numérique. Nous ferons rapport ici dans les semaines à venir pour obtenir votre point de vue.
En attendant, nous apprécions toujours votre contribution si vous avez quelque chose à partager. Vous pouvez faire vos commentaires dans la section Discussion de notre groupe GCcollab.

**Comment by MaryBethBaker** [comment]
Archiving this issue from 2018.
