### ISSUE TITLE
Digital Policy - Phase 2  / Politique numérique - phase 2 

### ISSUE THREAD

**Issue by SonyaRead** [canada-ca/welcome#36]
On behalf of the Treasury Board Secretariat, Government of Canada, thank you for your support during Phase 1 of the development of a new Treasury Board Digital Policy to help transition the Government of Canada into the digital era. 

Phase 1, the idea generation stage, of the policy development process concluded in late June. We were very pleased with the participation from both the public and government officials. We received a high volume of thoughtful feedback on what these rules and guidance might look like. 

We have now begun Phase 2, the development of policy requirements. In addition to reviewing the feedback from Phase 1, we conducted a line-by-line review of the existing sets of rules, and considered Government of Canada priorities and direction to develop proposed high-level policy directions regarding service, information technology, information management and cyber-security for a new Digital Policy. 

We continue to develop in the open, and we invite your reaction and comments to these proposed rules by September 11, 2018. Your feedback will support us in further developing these policy directions, as we move forward to seek endorsement from Deputy Ministers in late fall 2018.  

For background documents that summarize the proposed rules and the feedback received during Phase 1: https://open.canada.ca/en/blog/our-continuing-journey-develop-rules-and-guidance-digital-government 

If you have not done so already, we encourage you to join the Digital-Numérique discussion group at GCcollab.ca. You may also submit feedback directly, or request a GCcollab invitation, to Digital.Numerique@tbs-sct.gc.ca. 

Thank you for your ongoing support.   
 
---

Au nom du Secrétariat du Conseil du Trésor du gouvernement du Canada, nous vous remercions de votre soutien au cours de la phase 1 de l’élaboration d’une nouvelle politique du Conseil du Trésor visant à faciliter la transition du gouvernement du Canada à l’ère numérique. 

La phase 1, l’étape de génération d’idées, du processus d’élaboration de la politique a conclu à la fin de juin. Nous sommes très heureux de la participation du public et des représentants du gouvernement. Nous avons reçu un grand nombre de commentaires réfléchis illustrant ce à quoi ces règles et directives pourraient ressembler. 

Nous avons maintenant commencé la phase 2, l’élaboration des exigences de la politique. En plus d’examiner la rétroaction de la phase 1, nous avons effectué un examen ligne par ligne des ensembles de règles en place et nous avons considéré les priorités et la direction du gouvernement du Canada afin de développer des instructions de haut niveau proposées en matière de politique concernant le service, la technologie de l’information, la gestion de l’information et la cybersécurité pour une nouvelle politique numérique. 

Nous continuons à développer ouvertement et nous vous invitons à apporter vos réactions et vos commentaires à l’égard de ces règles proposées d’ici le 11 septembre 2018. Votre rétroaction nous soutiendra dans l’élaboration de ces orientations en matière de politique, à mesure que nous avançons en vue d’obtenir le soutien des sous-ministres à la fin de l’automne 2018.  

Our l'information sur le contexte qui résument les règles proposées et la rétroaction reçue au cours de la phase 1. https://ouvert.canada.ca/fr/blog/notre-parcours-vers-letablissement-des-regles-et-des-directives-regissant-le-gouvernement

Si vous ne l’avez pas déjà fait, nous vous encourageons à vous joindre au groupe de discussion Digital-Numérique sur le site GCcollab.ca. Vous pouvez également transmettre vos commentaires directement à : Digital.Numerique@tbs-sct.gc.ca ou demander une invitation à GCcollab. 
Merci de votre soutien continu.

**Comment by MaryBethBaker** [comment]
Archiving this issue.
