### ISSUE TITLE
Issue with trying to change Canada-ca repository wiki

### ISSUE THREAD

**Issue by wendyliao2018** [canada-ca/welcome#37]
Hi everyone, 

I am trying to edit and update the Canada-ca wiki page, more specifically the Draft Guiding Principles for Consultations and Public Engagement in English and French. However, it is not giving me the option to edit on the top corner, and when I fork it, it the repository does not show up in my repository.

@gcharest @pjackson28 @RachelMuston would it be possible to help me out with this? 

Thank you!

**Comment by RachelMuston** [comment]
Hey @wendyliao2018, 
What specifically are you trying to edit in the top corner?

**Comment by wendyliao2018** [comment]
Whoop! @MaryBethBaker broke in and fixed it :)  Thank you for your quick response @RachelMuston !

**Comment by RachelMuston** [comment]
@MaryBethBaker is an all star. :)
