### ISSUE TITLE
How to know about events and community?

### ISSUE THREAD

**Issue by renanbastos93** [canada-ca/welcome#41]
Well, I wish to go to study in Toronto to improve my English. But as I am a developer just like you, I want to know the calendar of events/ conference about technologies around the city. However, I want to know if is possible I participate with you in this community? So, I can improve my English and technical skills.

**Comment by MaryBethBaker** [comment]
Archiving this conversation.

**Comment by renanbastos93** [comment]
million years ago, kkk
no worries, thanks. see ya

**Comment by MaryBethBaker** [comment]
Toronto civic tech is always a good option: http://civictech.ca/
