### ISSUE TITLE
Do you list orgs that Gov Can contributes to? 

### ISSUE THREAD

**Issue by gmajan** [canada-ca/welcome#42]
moja global is an international collaboration but the Canadian Forest Service from Natural Resources Canada is a lead contributor and maintainer. Would it be useful to add moja global to the list of Canadian Gov Orgs on GitHub?

We have recognized the Canadian Government for its support by publishing your account in our read-me. See at the bottom of the page of https://github.com/moja-global/About-moja-global

Thank you.

**Comment by patcon** [comment]
I can't speak for org maintainers, but i would imagine this is only for gov depts? The canadian government collaborates on lots of initiatives, but I don't understand this to be the place to talk about those :)

**Comment by gcharest** [comment]
Interesting question. Maybe this would better fit in the [Open Resource Exchange](https://github.com/canada-ca/ore-ero)

**Comment by MaryBethBaker** [comment]
Archiving this issue.
