### ISSUE TITLE
Request to install GitKraken into the Org

### ISSUE THREAD

**Issue by nschonni** [canada-ca/welcome#44]
@delisma requested that the app get installed into the github org.
Do you want to give some background on why it should be installed?

**Comment by delisma** [comment]
I'm using GitKraken has a visual git editor (similar to GitHub Desktop). I don't think it should be installed, but access from a desktop app should be granted.

**Comment by nschonni** [comment]
OK, i'll close off https://github.com/orgs/canada-ca/policies/applications/231424
