### ISSUE TITLE
Install request for Netifly

### ISSUE THREAD

**Issue by nschonni** [canada-ca/welcome#45]
Request from @Borges-Porteous for design-system

https://github.com/apps/netlify/installations/new/permissions?request_id=72832&target_id=20973642

**Comment by nschonni** [comment]
I'm going to go ahead an approve it. If people are looking for it in other repos, please comment below

**Comment by nschonni** [comment]
@ux-tbs the request https://github.com/orgs/canada-ca/policies/applications/117514 is asking for private data access to the organization. What is this required for?

**Comment by patcon** [comment]
for whoever did this, netlify might work via github app, which is per-repo, instead of per-org scope :)
https://github.com/apps/netlify

**Comment by nschonni** [comment]
I've denied this since we don't have private repos, so this doesn't seem needed right now
