### ISSUE TITLE
Accessibility repository

### ISSUE THREAD

**Issue by shawnthompson** [canada-ca/welcome#47]
We would like to have a centralized repository to host information about accessibility related to the work the different departments are doing. This repo will be a gh-page site which uses CDTS to display the content in HTML. Preferred name would be `a11y`, so url would be Canada-ca.github.io/a11y.

Main contributors right now would me me and @bsouster, we would like to add more people later on.

Thanks,

Shawn Thompson
Conseiller technique en accessibilité Web | Web Accessibility Technical Advisor
Accessibilité TI | IT Accessibility
Innovation, information et technologie | Innovation, Information and Technology
Emploi et Développement social Canada | Employment and Social Development Canada

**Comment by nschonni** [comment]
I've created the initial repo off the template https://github.com/canada-ca/a11y and add you 2 as admins.
If you're looking for something else as the template or to rename it back to "accessibility" let me know.

**Comment by nschonni** [comment]
Closing since the repo has been created
