### ISSUE TITLE
feat: Authorization for Prose.io

### ISSUE THREAD

**Issue by delisma** [canada-ca/welcome#53]
---
name: Feature Request
about: feat: Authorization request for Prose.io on blog-dto and blogue-btn
title: 'feat: Authorization for Prose.io'
labels: enhancement
assignees: '@nschonni'

---

### Problem to solve
@ux-tbs Would like to authorize Prose in the canada-ca/blog-dto and canada-ca/blogue-btn repos to enable a new workflow.

### Intended users
@arianna-merritt
@adeyfarah
@delisma
@quidampepin
@dk-tbs
@LPipes4

### Proposal

I'll take any propositions from you
 
### Permissions and Security

It seems that we have to go through canada-ca organization for the authorization to work on an individual level. Also most of intended users don't seem to be member of canada-ca.

### What does success look like, and how can we measure that?
Simplest workflow possible for a non-coder contributor

**Comment by patcon** [comment]
Drive-by hot-take here from a rando non-gov dev :)

Development Seed / MapBox (who still run the prose.io infra, I believe) seem pretty trusted to me.

But if it's hard to get permission, you could:
1. Fork prose.io repo, as it run cleanly on GitHub Pages, and
2. Host your own heroku app for [Gatekeeper repo](https://github.com/prose/gatekeeper) which is the small piece that does auth and keeps track of credentials.

I would highly recommend just using prose.io, but in a pinch, you could do the above if there's someone who is ok to be responsible for maintainance 🤷‍♂️ 

Good luck!

**Comment by nschonni** [comment]
@delisma so I was looking to see if there was a pending install request, but poking around, it seems like there is no authorization at the org level required. The people go to http://prose.io/#canada-ca/blogue-btn or just prose.io and sign-in and just use it
