### ISSUE TITLE
New repo request - "tbs-cyber"

### ISSUE THREAD

**Issue by h701h** [canada-ca/welcome#57]
Hi, 

The TBS Cyber team is requesting a new repo called "TBS Cyber". 

- Repo needs to be private to start. 
- User "h701h" needs to be the admin

**Comment by nschonni** [comment]
Do you want the space in the title or do it kabab case like `tbs-cyber`

**Comment by nschonni** [comment]
Should this be owned by the existing Team https://github.com/orgs/canada-ca/teams/tbs-cyber

**Comment by nschonni** [comment]
Or a sub team of cyber like `tbs-cyber/tracker`

**Comment by h701h** [comment]
1. "tbs-cyber" is perfect
2. This shouldn't be linked to a team. But I also can't see who is in that team. 
3. AT this time. No team. Just private repo with me as admin.

**Comment by nschonni** [comment]
Repo has been created, and invite sent, so closing this one off
