### ISSUE TITLE
Can we add @prycrane as a member of canada-ca?

### ISSUE THREAD

**Issue by delisma** [canada-ca/welcome#61]
---
name: Canada-ca membership
about: Requesting a member addition to Canada-ca.
title: Can we add @prycrane as a member of canada-ca?
labels: enhancement
assignees:  @nschonni 

---

### Problem to solve

We want to add another member to the DTO team so they can access the projects section

### Intended users
@prycrane

**Comment by nschonni** [comment]
It looks like they were removed from the org ~5 days ago, but I've invited them back with the previous membership
![image](https://user-images.githubusercontent.com/1297909/189929940-ab08526b-6257-4a4a-a35b-dac338aac0be.png)
