### ISSUE TITLE
Pol.is test

### ISSUE THREAD

**Issue by kentdaitken** [canada-ca/welcome#7]
Thought it might be fun to give that platform a whirl ourselves. We should start with ~15 statements with a reasonable level of contentiousness. Suggest we use this thread to produce some, then I'll schedule a conversation via the platform. 

Statements (going meta for this, seems like a decent two-birds-one-stone on a topic we're all interested in):

- Online engagement will likely never be demographically representative
- Engagement should be demographically representative
- Online engagement will level the playing field for voices in a public policy/program/service discussion
- Engagement is impossible to measure because everyone has a different view of what "good outcomes" are
-  Engagement tools should be OSS
-   online engagement should be balanced with in-person

**Comment by kentdaitken** [comment]
An anonymous statement fairy provided these as well:

- Governments should allow completely anonymous participation
- Social media proves that most people will be comfortable telling the government their views online if enough other people are
- In elections, paper and pencil ballots are more secure than online voting
- Engagement tools should be OSS

**Comment by derekhoward** [comment]
Hey there, 
I'm super excited about testing pol.is and started a [test conversation](https://pol.is/69fnuffbkm) with my friends about electoral reform. I seeded the conversation with ~30ish statements based on comments that I found in the MPs reports from their respective town hall meetings on electoral reform [found here](http://www.parl.gc.ca/Committees/en/ERRE/StudyActivity?studyActivityId=9013025)

It could use more comments but I'm really curious what everybody thinks so far

**Comment by patcon** [comment]
For those who are interested in using pol.is in a more official capacity, you might want to +1 this feature request for multi-lingual comment support:
https://github.com/pol-is/issues/issues/7

**Comment by ThomKearney** [comment]
Has anyone looked at the accessibility of the tool?

**Comment by colinmegill** [comment]
Hi @ThomKearney, thanks for that question, could you point me towards documentation on your side re: standards the Canadian government is required to meet re: accessibility, and we'll send you back three things:

* What we have
* What we can do immediately
* What we'll need to put some work into

**Comment by ThomKearney** [comment]
Hi Colin, 
We have an internal standard on the topic https://www.tbs-sct.gc.ca/pol/doc-eng.aspx?id=23601 that looks for compliance on all [five WCAG 2.0 conformance requirements](http://www.w3.org/TR/WCAG20/#conformance-reqs):

**Comment by mgifford** [comment]
I've taken a brief look at the accessibility of the tool and will be recommending some improvements in accessibility.

**Comment by colinmegill** [comment]
Excellent! Thank you both.

**Comment by helendaniels** [comment]
Kent
for your list?
The Federal Government can engage as meaningfully as a municipal government.
Government should be in the business of public engagement.
People really want to talk to the government, they are just waiting for the right tool.

**Comment by patcon** [comment]
some version of:

- online engagement should only be used as far as agenda-setting for in-person

**Comment by kentdaitken** [comment]
@patcon @helendaniels  Awesome, thank you. I think we're there. I'll seed a discussion asap - perhaps tomorrow morning.

**Comment by patcon** [comment]
Might be interesting to contact the hosts of this conference, and maybe see if they'd be interested in sending out the survey in one of their (presumed) follow-up emails:
http://www.publicconsultationcanada.com/

**Comment by patcon** [comment]
Hey all!

Since it's kinda related, my friend @derekhoward and I just launched this pilot, inspired by the MyDemcracy.ca project: https://mydem0cracy.ca/

Please feel free to participate, retweet (if you think it worthy), and offer feedback to a collaborative inbox we set up at polis-canada@googlegroups.com

We've also got an issue queue for upcoming tasks, if you know anyone who might want to haaaalp :)
https://github.com/CivicTechTO/MyDem0cracy.ca-site/issues (so if you like github, feedback is beter in public :)

Thanks all!

**Comment by laurawesley** [comment]
How many interactions before it starts to show trends? Not sure if we can get enough participation on engaging about engaging @kentdaitken I'd love for us to come up with a topic that is slated for future consultation so we can pilot the tool and put a concerted effort into it as a primary/central place to engage.

What criteria would make for a good demo project?

**Comment by kentdaitken** [comment]
@laurawesley I was thinking that for the purposes I was suggesting - getting a feel for a platform that throws out the "moar comments please" starting point - weighing in (anonymously if preferred but truthfully) on mydem0cracy.ca will work better than trying to rustle people up for a smaller-scale test. Whicih I've done - just a few minutes to go through the comments, possibly add new ones, then start to play with the findings on majority opinion groupings.

And, of course, not that we should privilege any platform. But thought it an interesting model (with a unique set of principles and hypotheses about online deliberation) worth exploring. My working theory about the platform would be that it's suited to questions with multiple camps but different elements within those camps, but the biggest one is scale - anything over, say, 250-300 people where deliberative, text-based discussions start to fall apart.

**Comment by colinmegill** [comment]
Indeed. Here's a larger example of a divisive issue (Uber) being discussed
as a scale in Taipei: https://pol.is/3phdex2kjf, one of the features of the
system is that the interaction and the insights follow the same patterns as
scale increases, while scale breaks other forms of citizen engagement.
We're working to make every aspect of scale manageable, from moderation and
curation of comments to metadata collection, insight synthesis and
reporting, even if 100,000 people show up.

While this conversation is in Mandarin, you can use Google Translate in
Chrome, and there is a debrief in English here:
https://blog.pol.is/uber-responds-to-vtaiwans-coherent-blended-volition-3e9b75102b9b

**Comment by colinmegill** [comment]
@laurawesley @kentdaitken I'm happy to help brainstorm ideas for a pilot, either here or on a call if that's helpful. @audreyt would also have good instincts on that. 

The more complex the better - election reform is a nice example. Do you have a list of upcoming consultations?

**Comment by MaryBethBaker** [comment]
Archiving this issue. Pol.is has been tested by folks in the GC for departmental consultations.
