### ISSUE TITLE
Can we remove a few members from Canada-ca org

### ISSUE THREAD

**Issue by delisma** [canada-ca/welcome#71]
@LauraLapointe 
@LPipes4 
@catalinaperezn 
@marcus-gil 

Are no longer associated with projects managed by @canada-ca/tbs-dto. We're not aware if they are working on other Canada-ca projects at the moment.

**Comment by donohuech** [comment]
Yes please go ahead and remove @delisma Thank you!

**Comment by delisma** [comment]
> Yes please go ahead and remove @delisma Thank you!

Please do not remove me. There's a period missing in that statement.
