### ISSUE TITLE
Add Dawn and Linda to the org

### ISSUE THREAD

**Issue by MrDeshaies** [canada-ca/welcome#73]
Hi!
Dawn (@dawnhall15) and Linda (@Linda-Dam) will be helping with the AIA. Can you please add them to the canada-ca org?

Merci!
Benoit

**Comment by nschonni** [comment]
Invites have been sent, along with membership to the aia-js-team, which gives them "Maintain" access to the repo

**Comment by CeeLau** [comment]
hi, can you add us to the org for service and digital performance work? 

Jane-lu-ce (Jane Lu)
Md - tbs (Miranda Dyck)
Ceelau (Christine Lau)
Ge-tbs (Greg Erickson)
kfletche (Kyle Fletcher)
Nd-tbs (Natasha Dsouza)
Shamnnadi (Shalom Nnadi)
Francesca-patten (Francesca Patten)
Debbie-stat (Debora Loccisano)
