### ISSUE TITLE
Intersection of machine learning, and public policy

### ISSUE THREAD

**Issue by patcon** [canada-ca/welcome#8]
Reticketed from https://github.com/canada-ca/welcome/issues/4#issuecomment-263865924 (as I'm sure others are eager to chase the thread here, where we don't have to worry about being on-topic with something else :) )

@dyomides said:

> @laurawesley Fascinating!!!
> I'm a big believer that AI (machine learning) is the right tool at the right time for so many different aspects of government. It can address the large exodus of people about to leave the public service; it can process large quantities of data unlike us which means it could flag files/applications that are risky, give them a score so that humans can act on the ones that require our attention (Gs&Cs should be paying attention to this); it can communicate on behalf of us with regards to questions that get asked often (SMS, messaging services, etc); it could also reduce the financial burden of supporting 2 official languages both externally as well as internally.
>
> I've been keeping an eye on its evolution and absolutely believe we should playing in this space if we want to improve dramatically in the next few years especially when it comes to quality of service. Never thought to use it for public policy making but truthfully this type of tech is limitless.
>
> I would start by identifying a key area/problem space that we would want to tackle with machine learning (ESDC is possibly playing in this space btw, had a convo with a really nice reverse mentor on this subject a few weeks ago. Then we'd need to put the right resources on the task, such as hiring students that study in the field of AI/math and pair them with various domain experts, a true collaborative approach. At the beginning it is all about preparing data into sets to teach the machine how to properly process the data. The goal is to train it to the point that it can be put to use. Of course this is all based on the limited reading and understanding I have of the subject.
>
> Initial thoughts anyway, definitely the direction the GC needs to go in! :)

**Comment by patcon** [comment]
As I understand it, there are two tools that are particularly relevant:

1. [Pol.is](pol.is/home). Open source. Really innovative team. Main focus is consultation and government. Used by vTaiwan as part of framework for stewarding new laws.
2. [remesh](https://remesh.ai/#platform-container). Closed source. Pretty, but philosophically seems kinda vision-less. Main focus is market research and customer support.

Right now, I'm truly excited about pol.is. I'm excited for remesh only in that it helps us see the puck we can skate toward (yay hockey analogies). Remesh's conversational UI makes me realize that this technology could truly be the basis of conversing with a citizenry as if they were a single entity. This is the layer of abstraction that could allow policy makers to start to interact with the electorate as if it were a person sitting across the conference table in a small meeting. This could be the seed of true agility in consultations, imho.

cc: @dyomides (I really did love you comment, and I'm sure others are eager to chase the thread here, where we don't have to worry about being on-topic with something else :) )

**Comment by patcon** [comment]
Related: https://medium.com/@supergovernance/update-1-0-and-go-cb61cbdf438e

**Comment by MaryBethBaker** [comment]
Archiving this thread.
