### ISSUE TITLE
Should gov partner with libraries for public engagement? 

### ISSUE THREAD

**Issue by laurawesley** [canada-ca/welcome#9]
Yesterday I visited the vibrant and modern Halifax Public Library. I live-tweeted my musings as I climbed the stairs to the top floor. I was surprised at the positive reaction to one Tweet in particular :

Pondering the potential of partnering with libraries for public engagement 

Dominique captured a few of the reactions in this storify: https://storify.com/clearerworld/conversation-avec-resultsjunkie-kentdaitken-trboum

People shared articles, stats and ideas. They mentioned digital services they appreciate from their local library. They offered to help explore the topic more, so here's a place we can do so!

Super excited to see where this conversation takes us!

**Comment by ThomKearney** [comment]
I have often thought that Libraries could play a key role in digital literacy and other things related to open and digital gov. Some already do.  The issue for me has been how to support municipal libraries from the federal level?

**Comment by MaryBethBaker** [comment]
I'm going to leave this ticket open and tag it with an owner shortly.

**Comment by laurawesley** [comment]
Can I like a tag (wishlist) :)

**Comment by ThomKearney** [comment]
I am imagining a national network of libraries that serve as local hubs for democracy across levels. Hyper local, municipal, regional, provincial, territorial, first nation, federal, international.

**Comment by jpmckinney** [comment]
Existing networks/associations of libraries include the Canadian Federation of Library Associations, Ontario Library Association, Canadian Urban Libraries Council, Canadian Association of Research Libraries.

**Comment by laurawesley** [comment]
I met the Chief Librarian for a big city library who said the libraries are really well-connected. They are a great information distribution hub to tap into. Maybe we could document some high level use cases and then find out the path of least resistance for how to tap into this amazing resource to increase awareness of government consultations and engagement opportunities.

**Comment by ThomKearney** [comment]
Edmonton public library is one that I have heard has done some interesting things in terms of digital literacy and probably in other areas as well.

**Comment by patcon** [comment]
Re: intersection of libraries and open gov. Toronto Public Library has been leading a weekly breakout group at Civic Tech Toronto hacknights, and building their upcoming "[Digital Innovation Hub](http://www.torontopubliclibrary.ca/using-the-library/computer-services/innovation-spaces/) booking system" with citizens. (Ironically, phone and in-person bookings only, right now.)

Another team (unaffiliated with library team) has spun off from the [MyDem0cracy.ca](https://mydem0cracy.ca/) project, and is working more generally on creating shared public infrastructure for running citizen-led consultations. So those groups are already sharing workspace, even if not working together yet :)

**Comment by MaryBethBaker** [comment]
Archiving this issues.
